### ISSUE TITLE
Hosting on Heroku

### ISSUE THREAD

**Issue by LISK819129** [RisingGeek/twitter-clone#1]
Hey so I really loved this project, but I have a few questions reagrdig this as im pretty new here..

The readme file explains the method to run it locally, can you please show / tell how to deploy / run this on Heroku?

Also, there is a link to the backend of the same, while running it / deploying it to an hosting service like heroku, should I paste both main and backend files together in a folder and push it?

Hope someone helps me with this..thanks <3

**Comment by RisingGeek** [comment]
You can refer to Heroku's documentation for deploying:
[https://devcenter.heroku.com/articles/deploying-nodejs](https://devcenter.heroku.com/articles/deploying-nodejs)
I have deployed the frontend on Netlify & backend on heroku
You don't need to combine the backend files. You can deploy both of them separately

**Comment by LISK819129** [comment]
Alright thx bud
